/**
 * Parse .env file content into key-value pairs
 */
export function parseEnvFile(content: string): Array<{ key: string; value: string }> {
  const lines = content.split(/\r?\n/);
  const variables: Array<{ key: string; value: string }> = [];

  for (const line of lines) {
    // Skip empty lines and comments
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    // Find the first = sign
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();

    // Remove surrounding quotes if present
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    // Handle escaped characters in double-quoted strings
    if (value.includes("\\")) {
      value = value
        .replace(/\\n/g, "\n")
        .replace(/\\r/g, "\r")
        .replace(/\\t/g, "\t")
        .replace(/\\\\/g, "\\")
        .replace(/\\"/g, '"');
    }

    if (key) {
      variables.push({ key, value });
    }
  }

  return variables;
}

/**
 * Generate .env file content from variables
 */
export function generateEnvFile(
  variables: Array<{ key: string; value: string }>,
  options?: {
    projectName?: string;
    envName?: string;
    includeHeader?: boolean;
  }
): string {
  const lines: string[] = [];

  if (options?.includeHeader !== false) {
    lines.push("# Generated by SecretBox");
    if (options?.projectName) {
      lines.push(`# Project: ${options.projectName}`);
    }
    if (options?.envName) {
      lines.push(`# Environment: ${options.envName}`);
    }
    lines.push(`# Date: ${new Date().toISOString()}`);
    lines.push("");
  }

  for (const { key, value } of variables) {
    // Quote values that contain spaces, quotes, or special characters
    const needsQuotes =
      value.includes(" ") ||
      value.includes('"') ||
      value.includes("'") ||
      value.includes("\n") ||
      value.includes("=") ||
      value.includes("#");

    if (needsQuotes) {
      // Escape special characters and wrap in double quotes
      const escaped = value
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")
        .replace(/\t/g, "\\t");
      lines.push(`${key}="${escaped}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }

  return lines.join("\n");
}
